services:
  client-db:
    image: postgres:16
    container_name: client-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: clients
      POSTGRES_USER: client_user
      POSTGRES_PASSWORD: client_pass
    volumes:
      - client-db-data:/var/lib/postgresql/data

volumes:
  client-db-data: