server:
  port: 8081

spring:
  application:
    name: client-service

  datasource:
    url: jdbc:postgresql://localhost:5434/clients
    username: client_user
    password: client_pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
